### ISSUE TITLE
Redesign documentation of the editor

### ISSUE THREAD

**Issue by eyworldwide** [oasis-engine/oasis-engine.github.io#110]
## 规则
- 提交方式：统一提PR到 0.4 分支 https://github.com/oasis-engine/oasis-engine.github.io/tree/0.4/docs  @czizzy @zhang2333 负责审核，完成之后 粘贴 PR 地址到以下分工TODO list 项后。
- 文件命名方式：editor-标题.zh-CN.md
- 重点突出下编辑器中如何使用，一些概念可以直接跳到 runtime 的文档
- 写作工具：Typora，教程文档 ：https://yuque.antfin-inc.com/oasis3d/qgxpw6/oggs06
- 截图工具：iShot（序号、高亮功能很实用） https://www.better365.cn/ishot.html
- 录屏工具：https://www.cockos.com/licecap/

## 文档编辑建议
- 图片设置宽或高，使用形如 `<img height="200" src="xx" />` （或者用 Typora 设置）

## 分工
@czizzy 

- [x]  编辑器 - 检查器面版 https://github.com/oasis-engine/oasis-engine.github.io/pull/155
- [x]  项目 https://github.com/oasis-engine/oasis-engine.github.io/pull/155

@zhang2333

- [x]  编辑器 - 资产面板 #161 

@MrKou47

- [x]  编辑器 - 菜单栏 https://github.com/oasis-engine/oasis-engine.github.io/pull/170
- [x]  编辑器 - 节点树 https://github.com/oasis-engine/oasis-engine.github.io/pull/162

@gz65555

- [x]  编辑器 - viewport #151 
- [x]  发布 #176 

@eyworldwide

- [x]  介绍 - 关于 Oasis Editor #159
- [x]  介绍 - 快速上手 #159
- [x]  组件 - 粒子 #159

@GuoLei1990

- [x]  资产 - 纹理 #145
- [x]  组件 - 相机 #145 

@zhuxudong

- [x]  组件 - gltf    #112 
- [x]  资产 - 模型  #112 
- [x]  资产 - 材质  #112

@singlecoder

- [x]  组件 - sprite #156 
- [x]  组件 - mask #156 
- [x]  组件 - mars #156 
- [x]  资产 - sprite #156 
- [x]  资产 - mars #156 

@cptbtptpbcptdtptp

- [x]  组件 - 光 #158 
- [x]  组件 - 碰撞体 #158 
- [x]  资产 - 立方纹理 #158 

@luzhuang

- [x]  脚本 #150 
- [x] 事件通信 #150  

@johanzhu

- [x]  编辑器 - 资产库 #147 
- [x]  组件 - spine #147 
- [x]  资产 - spine #147 

@yangfengzzz

- [x]  组件 - 几何体模型 #160

**Comment by zhang2333** [comment]
Refactoring: [Editor Docs](https://github.com/oasis-engine/editor/issues/106).

We will close the issue when the docs has been replaced at website.

**Comment by zhang2333** [comment]
目录重构 PR：#182
