### ISSUE TITLE
Deploy a mirror site in China

### ISSUE THREAD

**Issue by eyworldwide** [oasis-engine/oasis-engine.github.io#12]
Visiting github.io is slow in China. We must deploy a mirror site for Chinese developers.

**Comment by husong-sudo** [comment]
- Use [gitee](https://gitee.com/) to deploy a site in China.
- Use cloudfare to speed up accessing static website.

**Comment by husong-sudo** [comment]
> * Use [gitee](https://gitee.com/) to deploy a site in China.
> * Use [cloudfare](https://cloud.tencent.com/developer/article/1774198) to speed up accessing static website.

- I have deploy a [website](https://oasis-engine.gitee.io/oasis-website/#/) in China
- cloudflare can only accelerate second-level domain

**Comment by husong-sudo** [comment]
@eyworldwide Still need a link to the mirror #15
