### ISSUE TITLE
Error in documentation sample code

### ISSUE THREAD

**Issue by Mcnwork2018** [oasis-engine/oasis-engine.github.io#20]
**Version**
0.2
**Reproduction link**
https://oasisengine.cn/#/0.2/manual/zh-cn/tools/event
**Steps to reproduce**
None.
**What is expected?**
Change "on" to "once".
**What is actually happening?**
Error in documentation sample code.
<img width="271" alt="屏幕截图 2021-05-06 113519" src="https://user-images.githubusercontent.com/37660444/117238336-40f73100-ae5f-11eb-9917-d0c83a954e31.png">

**Comment by cptbtptpbcptdtptp** [comment]
We have fixed it, thanks
