### ISSUE TITLE
Englishization of documents

### ISSUE THREAD

**Issue by GuoLei1990** [oasis-engine/oasis-engine.github.io#98]
@gz65555 

- [x] #194
- [x] #195
- [x] #196
- [x] #197
- [x] #198

@luzhuang 

- [x] #199
- [x] #200
- [x] #201
- [x] #202
- [x] #203

@cptbtptpbcptdtptp 

- [x] #204
- [x] #205
- [x] #206
- [x] #212 

@GuoLei1990 

- [x] #207
- [x] #208
- [x] #209
- [x] #210
- [x] #211

@eyworldwide 

- [x] #213
- [x] #214
- [x] #215
- [x] #216
- [x] #217

@johanzhu 

- [x] #218
- [x] #219

@zhuxudong 

- [x] 【Englishization】光照
- [x] 【Englishization】纹理资源
- [x] 【Englishization】glTF
- [x] 【Englishization】帧缓冲拾取
- [x] 【Englishization】材质
- [x] 【Englishization】自定义材质
- [x] 【Englishization】纹理烘焙
- [x] 【Englishization】导出 Unlit 材质

@singlecoder 

- [x]  #243 
- [x]  #243 
- [x]  #243 
- [x]  #243 
- [x]  #243 

@yangfengzzz 
- [x] #220
- [x] #221

**Comment by cptbtptpbcptdtptp** [comment]
@gz65555 

- 安装 Oasis Engine
- 绘制一个立方体
- 加载一个 3D 模型
- 资源管理与加载
- 支付宝/淘宝小程序

@luzhuang 

- 第一个脚本模型
- 脚本
- 动画切片
- 实体与组件

@cptbtptpbcptdtptp 

- 第一个游戏
- 相机
- 射线投射
- 控制器

@GuoLei1990 

- 引擎
- 克隆
- Model Mesh
- Buffer Mesh
- 事件系统
- 帧缓冲拾取

@eyworldwide 

- 画布
- 场景
- 粒子动画
- 统计面板
- Lottie

@johanzhu 

- 变换
- Spine

@zhuxudong 

- 光照
- 网格渲染器
- 骨骼动画
- 纹理资源
- 材质
- 自定义材质
- 纹理烘焙
- 导出 Unlit 材质

@singlecoder 

- 基础几何体
- 精灵渲染器
- 精灵遮罩
- 碰撞检测
- 精灵资源
- 数学库

**Comment by czizzy** [comment]
editor:

@czizzy 
- 介绍 - 关于 Oasis Editor
- 介绍 - 快速上手
- 编辑器 - 检查器面版
- 项目

@zhang2333 
- 编辑器 - 资产面板
- 资产 - 上传资产

@MrKou47 
- 编辑器 - 菜单栏
- 编辑器 - 节点树

@gz65555 
- 编辑器 - viewport
- 编辑器 - 预览
- 组件 - 相机
- 发布

@eyworldwide 
- 脚本编辑

@GuoLei1990 
- 资产 - 纹理

@zhuxudong 
- 组件 - gltf
- 资产 - 模型
- 资产 - 材质

@singlecoder
- 组件 - sprite
- 组件 - mars
- 资产 - sprite
- 资产 - mars

@cptbtptpbcptdtptp 
- 组件 - 光
- 组件 - 碰撞体
- 资产 - 立方纹理

@luzhuang
- 组件 - 脚本
- 脚本 - 事件通信

@johanzhu
- 编辑器 - 资产库
- 组件 - spine
- 资产 - spine

@yangfengzzz 
- 组件 - 几何体模型
- 组件 - 粒子
